#!/usr/bin/env bash
# Generated by Chock. Refuses `git commit` and `gh pr create|edit` commands whose message
# or PR body narrates the development process instead of describing the change. Scans inline
# text (-m/--message, -b/--body, and combined short clusters like -am) and, when the file is
# readable, -F/--file and --body-file. Best-effort guard: a deny-list of process-leak markers,
# deliberately narrow so a false block stays rare -- edit MARKERS below to fit your team's
# vocabulary; the content is yours. The gh slice covers the CLI only; a PR body set through
# the web UI, or one a harness appends AFTER the tool call, is out of this guard's reach --
# that is what the CI backstop (scanning the PR body on the pull_request event) is for.
set -eu

# Applies to `git commit` and `gh pr create|edit`. The invoked command is argv[0]; a later
# 'git'/'gh' appearing as an argument value (e.g. `echo git commit -m "..."`) must not
# trigger. For git the subcommand may follow global options (`git -c x=y commit`), so scan
# for a bare 'commit' token; for gh, match the `pr create|edit` prefix. A stray 'commit'
# operand (`git log commit`) is harmless: with no -m/-b the collected text is empty and the
# guard exits allow.
# Skip transparent command prefixes (sudo, command, env VAR=val, nice, ...) so a wrapped
# `command git commit` / `sudo git commit` / `env X=y git commit` is still detected, while
# a non-command like `echo git commit` -- whose first token is not a wrapper -- is correctly
# ignored. Value-taking wrapper flags (sudo -u X) remain best-effort, like the rest of this
# guard; the commit-time gate and CI are the backstop.
i=1
while [[ $i -le $# ]]; do
    case "${!i}" in
        sudo|doas|command|env|nice|nohup|time|stdbuf|setsid|ionice) i=$((i+1)) ;;
        *=*) i=$((i+1)) ;;
        *) break ;;
    esac
done
cmd="${!i:-}"

is_target=0
case "$cmd" in
    git)
        for arg in "$@"; do
            [[ "$arg" == "commit" ]] && { is_target=1; break; }
        done
        ;;
    gh)
        saw_pr=0
        for arg in "$@"; do
            case "$arg" in
                pr) saw_pr=1 ;;
                create|edit) [[ "$saw_pr" -eq 1 ]] && { is_target=1; break; } ;;
            esac
        done
        ;;
esac

# Marker phrases that describe the conversation rather than the change. Matched
# case-insensitively as substrings. The session-URL marker is the concrete leak this
# policy was hardened for: agent harnesses append a claude.ai/code/session link to PR
# bodies, publishing a private session identifier on a public repo forever. Defined here,
# before the raw-text fallback below, so that fallback (which runs before the positional
# is_target==0 exit) sees a populated array rather than an empty one under `set -u`.
MARKERS=(
    "claude.ai/code/session"
    "user asked"
    "user asks"
    "user requested"
    "user said"
    "user wants"
    "the user's"
    "per the conversation"
    "per our conversation"
    "this conversation"
    "in this session"
    "session summary"
    "chat transcript"
    "maintainer decision"
    "maintainer asked"
    "as agreed with"
    "docs/internal/"
)

# A shell wrapper (sh -c "...", bash -c "...") hides the real git/gh invocation and its
# message inside ONE opaque argv token -- shlex has already collapsed the quoted inner
# command by the time this guard sees argv, so cmd is "sh"/"bash"/"zsh"/etc, never
# "git"/"gh", and the positional scan above never runs. Scoped to cmd actually being a
# shell interpreter (not, say, "echo", which is already correctly excluded by keying on
# argv[0] and must stay excluded here too -- printing "git commit ..." is not running it)
# so this does not re-open the exact false positive that keying on argv[0] exists to close.
# Fall back to scanning the raw command text for the same markers when it looks like a
# wrapped commit/PR composition. Coarser (a marker anywhere in the wrapped command, not
# only inside the message argument) but not blind to it; the message-fragment extraction
# above stays the precise path for the direct-invocation case.
case "$cmd" in
    sh|bash|zsh|ksh|dash)
        if [[ "$is_target" -eq 0 && -n "${CHOCK_RAW_COMMAND:-}" ]]; then
            raw_lower="$(printf '%s' "$CHOCK_RAW_COMMAND" | tr '[:upper:]' '[:lower:]')"
            case "$raw_lower" in
                *git*commit* | *gh*pr*create* | *gh*pr*edit*)
                    for marker in "${MARKERS[@]}"; do
                        if [[ "$raw_lower" == *"$marker"* ]]; then
                            echo "BLOCKED: commit message or PR body narrates the development process ('$marker'). Describe the change itself; keep conversations, plans, session links and decision trails out of published history -- on a public repo every message is published forever. If this phrase is legitimate here, edit the MARKERS list in this guard." >&2
                            exit 1
                        fi
                    done
                    ;;
            esac
        fi
        ;;
esac

if [[ "$is_target" -eq 0 ]]; then
    exit 0
fi

collect=""
expect_msg=0
expect_file=0
for arg in "$@"; do
    if [[ "$expect_msg" -eq 1 ]]; then
        collect="$collect $arg"
        expect_msg=0
        continue
    fi
    if [[ "$expect_file" -eq 1 ]]; then
        [[ -r "$arg" ]] && collect="$collect $(cat -- "$arg" 2>/dev/null || true)"
        expect_file=0
        continue
    fi
    case "$arg" in
        -m|--message|-b|--body) expect_msg=1 ;;
        --message=*) collect="$collect ${arg#--message=}" ;;
        --body=*) collect="$collect ${arg#--body=}" ;;
        -m?*) collect="$collect ${arg#-m}" ;;
        -b?*) collect="$collect ${arg#-b}" ;;
        -F|--file|--body-file) expect_file=1 ;;
        --file=*) f="${arg#--file=}"; [[ -r "$f" ]] && collect="$collect $(cat -- "$f" 2>/dev/null || true)" ;;
        --body-file=*) f="${arg#--body-file=}"; [[ -r "$f" ]] && collect="$collect $(cat -- "$f" 2>/dev/null || true)" ;;
        -F?*) f="${arg#-F}"; [[ -r "$f" ]] && collect="$collect $(cat -- "$f" 2>/dev/null || true)" ;;
        -[a-z]*)
            # Combined short cluster carrying -m (git) or -b (gh), e.g. `git commit -am "msg"`
            # or `-amMSG`. The value is the text after the FIRST m/b in the cluster, or the
            # next argument if nothing follows -- exactly how git/gh consume it.
            case "$arg" in
                *m*|*b*)
                    rest="${arg#*[mb]}"
                    if [[ -n "$rest" ]]; then
                        collect="$collect $rest"
                    else
                        expect_msg=1
                    fi
                    ;;
            esac
            ;;
    esac
done

if [[ -z "${collect// /}" ]]; then
    exit 0  # no inline message (editor flow): nothing to scan here
fi

lower="$(printf '%s' "$collect" | tr '[:upper:]' '[:lower:]')"
for marker in "${MARKERS[@]}"; do
    if [[ "$lower" == *"$marker"* ]]; then
        echo "BLOCKED: commit message or PR body narrates the development process ('$marker'). Describe the change itself; keep conversations, plans, session links and decision trails out of published history -- on a public repo every message is published forever. If this phrase is legitimate here, edit the MARKERS list in this guard." >&2
        exit 1
    fi
done

exit 0
