#!/usr/bin/env bash
# Generated by Chock. Refuses shell commands that write to CI/CD workflow config -- an
# agent must not weaken the automated checks that review its own work. Reads pass;
# `chock sync` and other tool-driven writes pass. Best-effort and coarse by design: when
# in doubt it blocks, and the fix is a two-step command or a human-approved run carrying
# 'chock: approved-config-change'.
set -eu

# Include the raw command string: Windows path forms and `bash -c "..."` payloads arrive
# here as one argument, and CHOCK_RAW_COMMAND carries the pre-split original.
full="$* ${CHOCK_RAW_COMMAND:-}"

# A human-approved change says so in the command itself, visibly.
case "$full" in
    *"chock: approved-config-change"*) exit 0 ;;
esac

# Whole-token raw writers (deleters/movers/editors). Word-split with globbing disabled so a
# `bash -c "rm ..."` payload is reached, and basename-normalized so /bin/rm and a bare rm
# both match.
_has_writer_token() {
    local tok
    set -f
    for tok in $1; do
        case "${tok##*/}" in
            tee | rm | mv | cp | chmod | truncate | patch | dd | ed | ex) set +f; return 0 ;;
        esac
    done
    set +f
    return 1
}
# Interpreters invoked in a *writing* form: a code/in-place flag AFTER an interpreter token
# within the same command string, so option order does not matter and a path-qualified
# interpreter still matches, yet a `bash -c` wrapper's own -c is not misattributed.
_interp_write() {
    local seen=0 tok
    set -f
    for tok in $1; do
        case "${tok##*/}" in
            python | python3 | perl | ruby | node) seen=1 ;;
        esac
        case "$tok" in
            -c | -e | --eval | -i | --in-place | -i.* | -pi | -pi.* | -ni | -ne)
                if [ "$seen" -eq 1 ]; then set +f; return 0; fi ;;
        esac
    done
    set +f
    return 1
}

# git subcommands that overwrite a tracked file from another ref or the index -- a write to
# the protected path even though no rm/cp/redirect token appears. `git checkout <ref> -- path`,
# `git checkout path`, and `git restore path` all replace the worktree file (e.g. reverting a
# workflow to a weaker earlier version). Only trips when BOTH git and a mutating subcommand are
# present; `git checkout <branch>`, `git status`, `git log` carry no protected path and pass the
# protected-path gate below regardless.
_git_worktree_write() {
    local has_git=0 has_mut=0 tok
    set -f
    for tok in $1; do
        case "${tok##*/}" in
            git) has_git=1 ;;
        esac
        case "$tok" in
            checkout | restore) has_mut=1 ;;
        esac
    done
    set +f
    [ "$has_git" -eq 1 ] && [ "$has_mut" -eq 1 ]
}

# Split a word-list string into clauses at command separators (';', '&&', '||', '|'). A
# writer verb or redirect in one clause must not condemn a protected-path mention in a
# DIFFERENT clause of the same command line -- `rm -f /tmp/x; cat .github/workflows/ci.yml`
# is a read, not a write, and `echo hi > /tmp/x; cat .github/workflows/ci.yml` never touches
# the protected path at all. Word-splitting alone only recognises a separator as ITS OWN
# token ("foo ; bar"), which misses the far more common "foo; bar" style, so a separator
# glued to the END of a token is peeled off too; one glued to a token's start or middle
# ("foo;bar", no space anywhere) is not, the residual limit of scanning words rather than
# parsing shell.
_clauses() {
    local tok body sep
    local -a cur=()
    set -f
    for tok in $1; do
        case "$tok" in
            ';' | '&&' | '||' | '|') body="" sep="$tok" ;;
            *'||') body="${tok%'||'}" sep="||" ;;
            *'&&') body="${tok%'&&'}" sep="&&" ;;
            *';') body="${tok%';'}" sep=";" ;;
            *'|') body="${tok%'|'}" sep="|" ;;
            *) body="$tok" sep="" ;;
        esac
        [[ -n "$body" ]] && cur+=("$body")
        if [[ -n "$sep" ]]; then
            [[ ${#cur[@]} -gt 0 ]] && printf '%s\n' "${cur[*]}"
            cur=()
        fi
    done
    [[ ${#cur[@]} -gt 0 ]] && printf '%s\n' "${cur[*]}"
    set +f
}

# Protected CI/CD paths, matched against one clause's backslash-normalized text. These are
# the files that define the automated checks on a change: workflow definitions, the
# composite actions they call, and the dependency-update automation.
_clause_protected_path() {
    local n="${1//\\//}"
    case "$n" in
        *.github/workflows/* | \
        *.github/actions/* | \
        *.github/dependabot.yml* | *.github/dependabot.yaml*)
            return 0
            ;;
    esac
    return 1
}

# In-place editors (substring) and the writer-token/interpreter-write/git-worktree-write
# helpers above, all scoped to ONE clause so a writer verb elsewhere in the command cannot
# pair with a protected path it never touches.
_clause_writer() {
    case "$1" in
        *"sed -i"* | *"--in-place"*) return 0 ;;
    esac
    _has_writer_token "$1" && return 0
    _interp_write "$1" && return 0
    _git_worktree_write "$1" && return 0
    return 1
}

# A `>`/`>>` redirect only writes to a protected path when the path is what it actually
# targets -- the token immediately after the operator (with an optional leading file
# descriptor number, with or without a space), not merely present somewhere in the same
# clause. Without this, `cat .github/workflows/ci.yml 2>/dev/null` (stderr suppressed, no
# write anywhere) and `grep ... .github/workflows/ci.yml 2>&1` (fd duplication) were both
# refused: the old check only tested whether SOME '>' and SOME protected substring occurred
# anywhere in the whole command, never whether the one redirected into the other.
_redirect_target_protected() {
    local n="${1//\\//}"
    local redirect_re='[0-9]?>>?[[:space:]]*'
    local target_re='(\.github/workflows/|\.github/actions/|\.github/dependabot\.yml|\.github/dependabot\.yaml)'
    [[ "$n" =~ $redirect_re$target_re ]]
}

protected=""
while IFS= read -r clause; do
    [[ -z "$clause" ]] && continue
    if _redirect_target_protected "$clause"; then
        protected=yes
        break
    fi
    if _clause_writer "$clause" && _clause_protected_path "$clause"; then
        protected=yes
        break
    fi
done < <(_clauses "$*"; _clauses "${CHOCK_RAW_COMMAND:-}")

if [[ -n "$protected" ]]; then
    echo "BLOCKED: shell write touching CI/CD workflow config is not allowed -- an agent must not weaken the automated checks that review its own work. Propose the change for human review, or approve by including 'chock: approved-config-change' in the command." >&2
    exit 1
fi

exit 0
